"""Initial migration

Revision ID: 3e1787b8b8d7
Revises: 
Create Date: 2024-10-25 11:19:14.497561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e1787b8b8d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_objects_id', table_name='objects')
    op.drop_table('objects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vertices', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='objects_pkey')
    )
    op.create_index('ix_objects_id', 'objects', ['id'], unique=False)
    # ### end Alembic commands ###
